//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace HelpDeskData
{
	/// <summary>
	/// Database       : HelpDeskDB
	/// Data Source    : tcp://Localhost:8080
	/// Server Version : 13.6
	/// </summary>
	public partial class HelpDeskDBDB : LinqToDB.Data.DataConnection
	{
		public ITable<Ticket> Tickets { get { return this.GetTable<Ticket>(); } }
		public ITable<User>   Users   { get { return this.GetTable<User>(); } }

		partial void InitMappingSchema()
		{
		}

		public HelpDeskDBDB()
			: base("HelpDeskData")
		{
			InitDataContext();
			InitMappingSchema();
		}

		public HelpDeskDBDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public HelpDeskDBDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public HelpDeskDBDB(LinqToDbConnectionOptions<HelpDeskDBDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="public", Name="Ticket")]
	public partial class Ticket
	{
		[PrimaryKey, NotNull    ] public string    TicketID    { get; set; } // text
		[Column,        Nullable] public string    Nama        { get; set; } // text
		[Column,        Nullable] public string    Email       { get; set; } // text
		[Column,        Nullable] public string    Priority    { get; set; } // text
		[Column,        Nullable] public string    Subject     { get; set; } // text
		[Column,        Nullable] public string    Message     { get; set; } // text
		[Column,        Nullable] public string    PIC         { get; set; } // text
		[Column,     NotNull    ] public bool      IsDelete    { get; set; } // boolean
		[Column,        Nullable] public string    Status      { get; set; } // text
		[Column,        Nullable] public DateTime? CreatedDate { get; set; } // date
		[Column,        Nullable] public DateTime? FinishDate  { get; set; } // date
		[Column,        Nullable] public string    Category    { get; set; } // text
		[Column,        Nullable] public string    Reply       { get; set; } // text
		[Column,        Nullable] public string    FileName    { get; set; } // text
	}

	[Table(Schema="public", Name="User")]
	public partial class User
	{
		[PrimaryKey, NotNull    ] public string ID         { get; set; } // text
		[Column,        Nullable] public string Nama       { get; set; } // text
		[Column,        Nullable] public string Password   { get; set; } // text
		[Column,        Nullable] public int?   Role       { get; set; } // integer
		[Column,        Nullable] public string Keterangan { get; set; } // text
		[Column,        Nullable] public string Email      { get; set; } // text
		[Column,     NotNull    ] public bool   IsDelete   { get; set; } // boolean
	}

	public static partial class TableExtensions
	{
		public static Ticket Find(this ITable<Ticket> table, string TicketID)
		{
			return table.FirstOrDefault(t =>
				t.TicketID == TicketID);
		}

		public static User Find(this ITable<User> table, string ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}

#pragma warning restore 1591
