//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace HelpDeskData
{
	/// <summary>
	/// Database       : HelpDeskDB
	/// Data Source    : tcp://Localhost:8080
	/// Server Version : 13.6
	/// </summary>
	public partial class HelpDeskDBDB : LinqToDB.Data.DataConnection
	{
		public ITable<PengajuanDana>      PengajuanDanas      { get { return this.GetTable<PengajuanDana>(); } }
		public ITable<PertanggungJawaban> PertanggungJawabans { get { return this.GetTable<PertanggungJawaban>(); } }
		public ITable<ProgramKerja>       ProgramKerjas       { get { return this.GetTable<ProgramKerja>(); } }
		public ITable<User>               Users               { get { return this.GetTable<User>(); } }

		partial void InitMappingSchema()
		{
		}

		public HelpDeskDBDB()
			: base("HelpDeskData")
		{
			InitDataContext();
			InitMappingSchema();
		}

		public HelpDeskDBDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public HelpDeskDBDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public HelpDeskDBDB(LinqToDbConnectionOptions<HelpDeskDBDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="public", Name="PengajuanDana")]
	public partial class PengajuanDana
	{
		[PrimaryKey, NotNull    ] public string    IDPengajuan             { get; set; } // text
		[Column,        Nullable] public string    NamaProker              { get; set; } // text
		[Column,        Nullable] public string    DanaPengajuan           { get; set; } // text
		[Column,        Nullable] public string    DanaPersetujuan         { get; set; } // text
		[Column,        Nullable] public string    NoRekening              { get; set; } // text
		[Column,        Nullable] public string    NamaBank                { get; set; } // text
		[Column,        Nullable] public string    NamaRekening            { get; set; } // text
		[Column,        Nullable] public DateTime? TanggalPengajuan        { get; set; } // date
		[Column,        Nullable] public string    TemaKegiatan            { get; set; } // text
		[Column,        Nullable] public string    JumlahPanitia           { get; set; } // text
		[Column,        Nullable] public DateTime? TanggalProses           { get; set; } // date
		[Column,        Nullable] public DateTime? TanggalTerealisasi      { get; set; } // date
		[Column,        Nullable] public string    IDProker                { get; set; } // text
		[Column,        Nullable] public string    File                    { get; set; } // text
		[Column,        Nullable] public string    Status                  { get; set; } // text
		[Column,        Nullable] public string    Keterangan              { get; set; } // text
		[Column,     NotNull    ] public bool      IsDelete                { get; set; } // boolean
		[Column,        Nullable] public bool?     IsLPJ                   { get; set; } // boolean
		[Column,        Nullable] public DateTime? TanggalAkhirTerealisasi { get; set; } // date
	}

	[Table(Schema="public", Name="PertanggungJawaban")]
	public partial class PertanggungJawaban
	{
		[Column, Nullable] public string    IDPertanggungJawaban { get; set; } // text
		[Column, Nullable] public string    IDProker             { get; set; } // text
		[Column, Nullable] public string    IDPengajuanDana      { get; set; } // text
		[Column, Nullable] public string    File                 { get; set; } // text
		[Column, Nullable] public string    DanaPemasukan        { get; set; } // text
		[Column, Nullable] public string    DanaPengeluaran      { get; set; } // text
		[Column, Nullable] public string    StatusKumpulOnline   { get; set; } // text
		[Column, Nullable] public string    StatusKumpulOffline  { get; set; } // text
		[Column, Nullable] public string    PesertaTerealisasi   { get; set; } // text
		[Column, Nullable] public DateTime? Deadline             { get; set; } // date
		[Column, Nullable] public DateTime? TanggalPengumpulan   { get; set; } // date
		[Column, Nullable] public string    Keterangan           { get; set; } // text
	}

	[Table(Schema="public", Name="ProgramKerja")]
	public partial class ProgramKerja
	{
		[PrimaryKey, NotNull    ] public string    ProkerID        { get; set; } // text
		[Column,        Nullable] public string    NamaLK          { get; set; } // text
		[Column,        Nullable] public string    Email           { get; set; } // text
		[Column,        Nullable] public string    Kategori        { get; set; } // text
		[Column,        Nullable] public string    DanaPengajuan   { get; set; } // text
		[Column,        Nullable] public string    DanaPersetujuan { get; set; } // text
		[Column,        Nullable] public string    PIC             { get; set; } // text
		[Column,     NotNull    ] public bool      IsDelete        { get; set; } // boolean
		[Column,        Nullable] public string    Status          { get; set; } // text
		[Column,        Nullable] public DateTime? CreatedDate     { get; set; } // date
		[Column,        Nullable] public DateTime? FinishDate      { get; set; } // date
		[Column,        Nullable] public string    Category        { get; set; } // text
		[Column,        Nullable] public string    Reply           { get; set; } // text
		[Column,        Nullable] public string    FileName        { get; set; } // text
		[Column,        Nullable] public string    ContactPerson   { get; set; } // text
		[Column,        Nullable] public string    TargetPeserta   { get; set; } // text
		[Column,        Nullable] public string    Keterangan      { get; set; } // text
		[Column,        Nullable] public string    NamaProker      { get; set; } // text
		[Column,        Nullable] public bool?     IsPengajuan     { get; set; } // boolean
		[Column,        Nullable] public bool?     IsLPJ           { get; set; } // boolean
	}

	[Table(Schema="public", Name="User")]
	public partial class User
	{
		[PrimaryKey, NotNull    ] public string ID         { get; set; } // text
		[Column,        Nullable] public string Nama       { get; set; } // text
		[Column,        Nullable] public string Password   { get; set; } // text
		[Column,        Nullable] public int?   Role       { get; set; } // integer
		[Column,        Nullable] public string Keterangan { get; set; } // text
		[Column,        Nullable] public string Email      { get; set; } // text
		[Column,     NotNull    ] public bool   IsDelete   { get; set; } // boolean
	}

	public static partial class TableExtensions
	{
		public static PengajuanDana Find(this ITable<PengajuanDana> table, string IDPengajuan)
		{
			return table.FirstOrDefault(t =>
				t.IDPengajuan == IDPengajuan);
		}

		public static ProgramKerja Find(this ITable<ProgramKerja> table, string ProkerID)
		{
			return table.FirstOrDefault(t =>
				t.ProkerID == ProkerID);
		}

		public static User Find(this ITable<User> table, string ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}

#pragma warning restore 1591
